apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: metallb
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.12.0
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 172.16.0.200-172.16.0.230
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.3
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.3
